### ISSUE TITLE
Consolidate configuration menus

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#112]
The different project settings options (there are currently two, which do different things) should be consolidated into a single menu.

![Screen Shot 2019-09-16 at 12 11 08 PM](https://user-images.githubusercontent.com/4060903/64978486-38fa1000-d87b-11e9-9f23-1e1d79eef464.png)

**Comment by casserni** [comment]
@wmhilton @P0lip Let's copy over the project settings (top right) into the cog menu

**Comment by dgrstl** [comment]
@wmhilton That makes a ton of sense. As it is there are project setting in both places and most people overlook the cog in the bottom left (which makes me thing top right is better placement). I propose one settings page with two sections, Project Settings, and Application Settings with the appropriate settings in each section. And I would change Application Settings to Studio Settings since it seems that's what we mean. I'd also suggest removing the theme toggle in the head icon menu since it is already in Studio settings.

**Comment by dgrstl** [comment]
@lottamus We can probably close this.

**Comment by rossmcdonald** [comment]
Fixed with upcoming v2 release.
