### ISSUE TITLE
Order of Properties is not consistent with file

### ISSUE THREAD

**Issue by MissingHandle** [stoplightio/studio#135]
In Stoplight Studio,

When I am in the "Write" mode for a Model that is an object,
And I cut and paste a property of an object in the editor,
And I then view the "Forms" mode,
I expect the order of the properties to be the order of properties I had them in the editor, top-to-bottom.
Instead, the field i cut-and-paste shows up at the bottom of the Forms mode.

When I am in the "Write" mode for a Model that is an object,
And I write a new property in the editor,
And I then view the "Forms" mode,
I expect the order of the properties to be the order of properties I had them in the editor, top-to-bottom.
Instead, the new property I wrote shows up at the bottom of the Forms mode.

**Environment (remove any that are not applicable):**
 - Studio version: Version 1.1.3 (1.1.3.6088)
 - OS: Mac OS Mojave 10.14.6 (18G87)
 - Browser: Desktop App

**Comment by ianbeck** [comment]
Please fix this. This is a major source of friction in our usage of Stoplight Studio, to the point that it is contributing to an internal movement to migrate to using Postman for API docs (all our endpoints are in there already, even if the documentation aspect is very basic and design-first approach is a lot harder). I am one of the few people in the office who is still doggedly using Stoplight Studio, but needing to restart the program every time I cut and paste something in code view because the Form view screws up the ordering in random ways (and then persists that bad ordering back to code, if I let the file save!) is a seemingly minor detail that's a real productivity killer.

Frankly, a WYSIWYG editor that doesn't treat the source code as the final source of truth isn't worth using.

**Comment by 0ttik** [comment]
I'd say that this is pretty critical bug to my use case which is editing model with lots of fields.  

I also would add to that a related feature request which is: 
1) Add UI drag&drop sorting in Model objects
2) Add alphabetical sorting which is quite useful for managing models with lots of fields

**Comment by mallachari** [comment]
@ianbeck @0ttik we are currently working on keeping order of properties so that should be added soon.

**Comment by P0lip** [comment]
Hey folks!
Wanted to let you know the fix has been merged recently, therefore one of the upcoming versions should come with improved ordering.

**Comment by lottamus** [comment]
We've just released Studio Desktop [v1.12](https://github.com/stoplightio/studio/releases/tag/v1.12.0) which includes a fix for this issue. Please feel free to re-open if you're still seeing the issue after upgrading.
