### ISSUE TITLE
Path params are not HTTP request method specific

### ISSUE THREAD

**Issue by adamculp** [stoplightio/studio#143]
**User story.**
As a use, I can specify that only GET or DELETE requests should have an 'id' path param, so that I can determine the record to interact with. Meanwhile POST would not need it, and PUT would likely have the id in the body. (I realize that DELETE may/should also have the id in the body. It's an example.)

**Is your feature request related to a problem?**

Path parameters, once defined, apply to all HTTP request methods. However, perhaps I want the [id] to be passed as a path param versus a query param. Such as, only with GET or DELETE, but not with POST or PUT. Since the path params are associated with the path entirely, this is not possible to add validation/requires.

**Describe the solution you'd like**
Move the Path param within each method type. Or perhaps add an additional conditional path param within each method type in addition.

**Comment by philsturgeon** [comment]
This is something you can take care of with Spectral rules. https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/getting-started/rulesets.md

Maybe add PATCH to that rule if you use that. :)

**Comment by adamculp** [comment]
Agreed. But would be nice if the gui moved the path param under each method, or possibly add an "append to path param" under each method for special cases for each method type while still allowing for a path param that is not method specific. Beginners already have difficulties learning, so this may make it easier to get up and running with less struggle.

**Comment by philsturgeon** [comment]
Wait I am not sure what you are asking. Could you do a sample document or a screenshot with annotations or something?

**Comment by marbemac** [comment]
I believe this is about path level path params versus operation level path params? 

We decided to support path level path params first, because this is most often what is desired - defining path params per operation is a more advanced use case that is rarely needed.

> As a use, I can specify that only GET or DELETE requests should have an 'id' path param, so that I can determine the record to interact with. Meanwhile POST would not need it, and PUT would likely have the id in the body. (I realize that DELETE may/should also have the id in the body. It's an example.)

In this situation, they would be completely different paths - one without an id, and one with an id. You can see this in action in the petstore example openapi, or our Stoplight todos example openapi file.

In the screenshot below, you can see that getting a single pet is defined with the path `/pets/{petId}` -> `GET` method, and creating a pet (which does not require an id path parameter) is defined with `/pets` -> `POST` method.

<img width="702" alt="Screen Shot 2019-10-03 at 7 44 40 PM" src="https://user-images.githubusercontent.com/847542/66173608-a0071b00-e616-11e9-8559-7fb8afa58320.png">

**Comment by adamculp** [comment]
The limiting portion of this is when trying to require a path param for one method while not marking it required for another.

I did not see a way to specify by a specific type as you've given as an example. I'll look more closely. Thanks.

**Comment by marbemac** [comment]
OpenAPI requires that path parameters are required. 

> For instance, maybe I want the ID to be required for PUT/PATCH/DELETE, but optional for GET, and not used at all for POST.

Maybe I'm misunderstanding, but is this basically what you are describing?

- Create user: `POST /users`
- List users: `GET /users`
- Update user: `PUT /users/{id}`
- Get user: `GET /users/{id}`
- Delete user: `DELETE /users/{id}`

Basically, that "optional" path param for GET = two different paths for the two different situations (list versus get single).

**Comment by adamculp** [comment]
Yes, that is correct. OK, so what you're saying is that /users/{id} and /users would be considered 2 different path definitions, rather than defining a single path /users/ with optional {id} that would be required for some methods? If so, that makes sense, and solves my issue. I assumed I would not be able to add 2 identical paths depending on params, but didn't try.
