### ISSUE TITLE
Query params limited to slashes, and not allow for colons

### ISSUE THREAD

**Issue by adamculp** [stoplightio/studio#144]
**User story.**
As a user, I can specify a query param in the form "?page:2" for pagination rather than "?page=2", so that I can know what page to use in pagination.

**Is your feature request related to a problem?**

We are following a specification that requires pagination to follow a "page:n" format versus "page=n" format. But in the studio it seems to default to "page=n" in the "Try it" area.

**Describe the solution you'd like**

It would be nice if the studio allowed for specifying the format of the path, or followed the pattern specified in the interface.

**Comment by philsturgeon** [comment]
I know of people doing ?value-= and ?value+= to create their own mini query language, and that is easily achievable.

```
      parameters:
        - name: limit+
          in: query
          required: false
          ...
```

Sadly what you want is not possible in OpenAPI. There is no keyword to say "use a colon instead of an =". 

We've done a few non-standard things through extensions (mostly to backport OAS3 functionality into OAS2, but this is a bit different. Is this a common specification, or an in house thing?

**Comment by adamculp** [comment]
I believe the use of 'page:n' is an artifact from the past. I still see it in some older apps. In modern apps I think "?page=n" query strings are the norm. I submitted the ticket because it was related to an old API I was using as I experimented with the Studio. Perhaps it can be closed and used for reference. Thank you.

**Comment by philsturgeon** [comment]
Gotcha, yeah. We'll have to close this one until OpenAPI add the ability to do that. Maybe in your API you could alias `?page:1` to `?page=1` in the code, then document the alias? Or something. Good luck 😅
