### ISSUE TITLE
Logged Out Studio Web Users Cannot Publish

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/studio#163]
**Describe the bug**

Trying to publish documentation for this repo (studio) from Desktop, I clicked the Publish button and was taken to Studio Web. I was logged out, but this was not clear other than a Sign Up button top right. 

<img width="607" alt="Screen Shot 2019-10-03 at 13 36 36" src="https://user-images.githubusercontent.com/67381/66124204-c9419000-e5b1-11e9-9b48-af197259cc6d.png">

It was initially not clear how to log in, but I found the option:

<img width="1243" alt="Screen Shot 2019-10-03 at 13 37 51" src="https://user-images.githubusercontent.com/67381/66124229-d52d5200-e5b1-11e9-983f-709c4f4fab2a.png">

I logged in, then was taken back to the empty project. I didn't notice it was empty, clicked "Publish", and it suggested deleting all the content. 

<img width="501" alt="image" src="https://user-images.githubusercontent.com/67381/66124294-03129680-e5b2-11e9-9cf7-049b16b27a69.png">

I figured maybe I need to pull (could not find the pull button for a while) but when I clicked it the pull failed:

<img width="514" alt="Screen Shot 2019-10-03 at 13 39 19" src="https://user-images.githubusercontent.com/67381/66124533-a4015180-e5b2-11e9-986d-5a0648ab1338.png">

I figured I would try in a icognito window (Firefox) but that caused a console error (I guess it cannot write in local storage?).

![Untitled](https://user-images.githubusercontent.com/67381/66126109-a665aa80-e5b6-11e9-8f87-77247d6bfa3d.gif)

> InvalidStateError: A mutation operation was attempted on a database that did not allow mutations

**Expected behavior**

1. It should be more clear that a user is not logged in. We could redirect users to login if they try to access studio?

2. When we log in it should maybe re-attempt processing/loading/whatever. It might not be required as it would not have processed when 1 is done.

3. Trying to publish in this scenario should not delete everything. Maybe there is no commit locally, and if that is the case the docs diff should error with a suggestion of pulling, or something, instead. Maybe not required when 1 is done as we would not get in this state?

**Environment (remove any that are not applicable):**
 - Studio version: 1.1.4
 - OS: mac OS 10.14.5 (18F132)
 - Browser: 69.0.1 (64-bit)

**Comment by philsturgeon** [comment]
Ok I found a workaround, users can switch branch to a random branch, then switch back to master and it'll work. Lowering severity to critical.

**Comment by philsturgeon** [comment]
@lottamus this one is a biggy and seems to be jumping between backlog and triage. I dont want this giant bug to slip through the cracks.

**Comment by StoplightDeb** [comment]
View in desktop (docs preview):
![Screen Shot 2019-11-20 at 2.08.11 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/8b7ee6f5-b65f-46e0-ba44-44caa443447b)

View on web (published docs):
![Screen Shot 2019-11-20 at 2.07.44 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/5040abad-2c5c-4b0a-a1b2-e9701513c2e2)

Just talking about the left contents bar differences - Please advise.

**Comment by StoplightDeb** [comment]
@lottamus @philsturgeon - what was the resolution to this / what are steps to test?

**Comment by chris-miaskowski** [comment]
@philsturgeon, to @StoplightDeb 's point this description could be improved.

It's a good example of something that at first sight seems to have enough information but lacks specific expectations on a closer investigation.

> It should be more clear that a user is not logged in. We could redirect users to login if they try to access studio?

Note how you actually ask a question rather than set the expectation. Words like **could** don't help QA because they don't tell what **must** be done. Similarly "should be more clear that a user is not logged in" does not tell what you expect. It's too ephemeral. There are so many ways to make it clear but none was specified.

Again, it's a great food for thoughts but the final description should include only the essential information. No speculations, no guesses. We need to assume that when an engineers takes the story they do exactly what's in the description.

I know you are overwhelmed with tasks and you are already doing great job with those stories. Your descriptions (and @marbemac 's) are closest to the ideal but there is still some room for improvement. I'm thinking about putting together a presentation for the entire company about this matter.

> When we log in it should maybe re-attempt processing/loading/whatever. It might not be required as it would not have processed when 1 is done.

"should **maybe** re-attempt" is not an expectation ;)
The problem isn't that you didn't make the effort to do a good job but that we don't have processes that would solidify this type of stuff. Ideally, you and Chris would follow up on this task before starting it and turn all "maybe" into "should/must". I know it's hard and time consuming. We'll get there together. You can count on my support!

> Trying to publish in this scenario should not delete everything. Maybe there is no commit locally, and if that is the case the docs diff should error with a suggestion of pulling, or something, instead. Maybe not required when 1 is done as we would not get in this state?

Similar issues like the ones mentioned before.

All in all I think the way you and @marbemac describe stories (and how @rossmcdonald describes bugs) is really the best what we have in the company. There is still some room for improvement (like I said). However, I think we can take these and promote the same level of high-quality across the board. Moreover, I think that this should be the basic level of seniority we should expect from excellent engineers in general. 

I have a Lunch & Learn back in my head that I will probably want to run next week(s). This issue is one of the biggest QA pains right now. We (I and Deb) keep talking about it every day and it is slowing us down.

***

Anyway, @StoplightDeb. For this particular story the expectations can be derived from the other story (https://github.com/stoplightio/studio/issues/164). Since now we allow publishing directly from Studio Desktop this is not an issue anymore. The expected behavior is that when user is not logged in they are presented with an information: "you must be logged in to publish". 

Which is, indeed, the case.

Of course I don't know **for sure** that this was the intention. But that's my guess taking into account all I know about this feature.

**Comment by philsturgeon** [comment]
I am not setting any expectations I am reporting a bug and offering some suggestions as to potential solutions. this might be an issue with your expectations of GitHub issues being a tool for QA, or maybe folks need to update issues once an implementation is picked, or maybe a comment could have been posted when something was decided. A PR will know exactly what implementation it has chosen, but an issue will often not, and you might need to get used to that.
