### ISSUE TITLE
Issue with using $refs in paths related to model

### ISSUE THREAD

**Issue by narozhniyy** [stoplightio/studio#183]
Hello guys, I have an issue with $refs relation path to model. Can you pls explain to me how to relate path response with already existing model. 
What I did:
1. Create a model
![Screenshot_19](https://user-images.githubusercontent.com/2987956/66484203-39b74800-eaaf-11e9-9ec7-557771089469.png)
2. After that I will create a path and add a $ref to model as a response.
![Screenshot_20](https://user-images.githubusercontent.com/2987956/66484301-62d7d880-eaaf-11e9-81b0-9eefad6009bd.png)
3 When I add openapi.yaml file content to openapi component to render documentation. I have error
![Screenshot_21](https://user-images.githubusercontent.com/2987956/66484506-c530d900-eaaf-11e9-9abf-6a573be734d0.png)

Expected result:
I should see model in path response.

**Comment by marbemac** [comment]
Hi @narozhniyy - good question. Swagger UI does not support references to other files, so you have to use the embedded model option when creating new models. Just click the "+" button in to the top toolbar, then model to bring up the new model form. From there, choose options similar to those shown in the screenshot below to define a model that is embedded inside the OpenAPI file (rather than created as a standalone separate file in the project). When everything is in a single OpenAPI file, things should work as expected inside of swagger ui.

We'll be making this a bit more clear in an upcoming release.

<img width="619" alt="Screen Shot 2019-10-09 at 11 14 39 PM" src="https://user-images.githubusercontent.com/847542/66538601-c6cbc280-eaea-11e9-9509-2c9eaa9dda32.png">

**Comment by narozhniyy** [comment]
@marbemac yes it works, thank you very much. You help me a lot.
