### ISSUE TITLE
Extract embedded models into model files

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#217]
**User story.**
As an API developer, I want to start splitting out the models from my current specifications into standalone models so that I can start reusing common models between different APIs. 

**Is your feature request related to a problem?**
Currently I would have to do this manually, which involves cutting-pasting JSON/YAML and manually writing JSON references. This can be time consuming and error prone.

**Describe the solution you'd like**
I would like to see an option added to the right-click menu on an embedded model for extracting. This would:

- Prompt me to select a directory for the file
- Create a new file in the provided directory, named based on the title of the model
- Cut the contents of the model from the spec and paste them into the standalone model
- Replace the model from the spec with a JSON reference to the new file

**Comment by philsturgeon** [comment]
This feature is a really good idea. You can move "Models" to "Common Models" with drag and drop, so we should allow drag and drop from "Embedded Models" to "Models" and "Common Models" too. Also a right click option for all these things, as drag and drop is not always clear, or possible for accessibility reasons. 

I edited the title because its not JSON Schema, and all of our tooling should and communication should reflect that.

**Comment by philsturgeon** [comment]
It might make sense to do this and #438 together instead of as two steps. This would make refactoring generated content so easy.

**Comment by philsturgeon** [comment]
Please show support for this feature in our new feature tracker if you're still interested. https://roadmap.stoplight.io/c/143-move-shared-models-to-standalone-models
