### ISSUE TITLE
Changing file extension on file doesn't update syntax checking

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#239]
**Describe the bug**
Changing the file type on a file after creation doesn't seem to update how the file syntax is verified.

**To Reproduce**
1. Create a `.spectral.json` file
2. Rename file to `.spectral.yml`
3. Start typing yaml

**Expected Behavior**
Since the extension has been updated, I shouldn't receive errors on file formatting.

**Actual Behavior**
Errors are raised in the Write view, making it seem like it's trying to parse the file in the wrong format.

**Workaround**
Refresh the window.

**Comment by chris-miaskowski** [comment]
I'm not sure it's 100% ok.

Try:
1. create .spectral.json
2. convert to .spectral.yaml
`No issues` ever

Try:
1. create .spectral.yaml
2. convert to .spectral.json
`no issues` until updated file

![updating-file-extention](https://user-images.githubusercontent.com/29548931/69252753-cb889980-0bb3-11ea-8341-e25a5da4d3fa.gif)

**Comment by P0lip** [comment]
@chris-miaskowski 
Don't try changes on Spectral config. It's kind of a special file, treated in a special way, therefore not very representative, so to speak.

Regarding issues - I did it on purpose, so that we don't redundantly re-parse the content.
Issues will be shown as soon as you make any change to the document.
I feel like it's a fair compromise?
@marbemac thoughts?

**Comment by StoplightDeb** [comment]
@P0lip - is this ready to test, or are we waiting for further info?

**Comment by chris-miaskowski** [comment]
Hey @StoplightDeb I think that's not what we're supposed to test. Like @P0lip said we should test any file other than spectral.yml. I will give it a look in a sec.

**Comment by chris-miaskowski** [comment]
Yup, got it now, it looks good on staging. Approving!
![change-file-format.gif](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/07ce73e0-7d4b-4d04-97c1-556375f0dde4)

**Comment by StoplightDeb** [comment]
@chris-miaskowski - can we get people to update the steps to repro in the ticket description so that we don't have to dig through the issue comments? because this was the actual steps to repro provided on the ticket:
<img width="253" alt="Screen Shot 2019-11-22 at 8 48 15 AM" src="https://user-images.githubusercontent.com/53012248/69435319-f46c7400-0d04-11ea-887e-cb0b74c667cf.png">

**Comment by P0lip** [comment]
@StoplightDeb @chris-miaskowski 
You are still welcome to test `.spectral.yml` or `.spectral.json`. My intention was to let you know that Spectral config file is treated a bit differently, i.e. it has its own validation mechanism and therefore messages displayed in diagnostics panel are generated in a different way. Hope that makes sense.
Let me know if you have any questions!

**Comment by StoplightDeb** [comment]
@chris-miaskowski - 
https://stoplight.testrail.io/index.php?/cases/view/5337
https://stoplight.testrail.io/index.php?/cases/view/5338

**Comment by marbemac** [comment]
@StoplightDeb where did we end up on this? Could you update with latest thoughts on areas to improve, or close if it meets expectations?

**Comment by P0lip** [comment]
It should be good to go now, my apologies for lack of notice.

**Comment by StoplightDeb** [comment]
Looks good on staging (again/still) 👍
