### ISSUE TITLE
Long articles in Studio Docs cause "On this page" items to be unreachable beyond viewport

### ISSUE THREAD

**Issue by stevenbennitt** [stoplightio/studio#244]
**Describe the bug**
For the "On this page" table of contents when the list is longer than the viewport, you cannot get to the rest of the anchors.

**To Reproduce**

1. Create a markdown doc with many h2's and h3's
2. Publish docs
3. View the doc

Example: https://bigcommerce.stoplight.io/docs/gh/stevenbennitt/dev-docs/docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

**Expected behavior**
I should be able to scroll within the "On this page" column independently of the content

**Environment (remove any that are not applicable):**
 - Studio v1.5.2-beta.12 (f2b69e2)
 - OS: Windows 10
 - Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by StoplightDeb** [comment]
@ssspear - ahoy!  I have a question for you - is the `On this page` section supposed to scroll independently of the main window?  I'm seeing that since the `On this page` section  is longer than the article, the `On this page` column won't scroll until the main window reaches the bottom (and then some) - [Video here](https://drive.google.com/open?id=1FniM94pK59DAN-t7qOJ1RBFuVfbl2RP7) - this is what Firefox and Safari do.  If this is right, then yay for these browsers!

Chrome - does not want to scroll for some reason! [Here is video](https://drive.google.com/open?id=1cY2qz8NWF0c_J0RIGPsykkVchGMEafr9)

**Comment by StoplightDeb** [comment]
@chris-miaskowski 
https://stoplight.testrail.io/index.php?/cases/view/6090
