### ISSUE TITLE
Add "Security" section to http operation docs

### ISSUE THREAD

**Issue by john-doe-2016** [stoplightio/studio#257]
In the new documentation, security does now appear (at least if based on headers). Is a good thing but it is not clearly stated that it concerns security:
![image](https://user-images.githubusercontent.com/20415788/69722800-4bfd4c00-1118-11ea-829f-ec7fa1cda67c.png)

And in this case, an API key is required, but two types may be used: a read only one, or a full (rw) one. Both use the same header.
![image](https://user-images.githubusercontent.com/20415788/69723181-42c0af00-1119-11ea-9aa1-585d41abe522.png)

The section inserted in header does not help understand it concerns security, and I think it should indicated the "security label" (FullAccessAPIKey or ReadOnlyAPIKey in this case) to help readers understand.

Relevant code: https://github.com/stoplightio/elements/blob/451f70c011c7c25db410c7aeda21a5480559c767/src/components/HttpOperation/Request.tsx#L26

**Comment by lottamus** [comment]
@john-doe-2016 instead of adding the relevant security to the Headers and Query sections of Docs, what do you think if we just added a "Security" section at the top?

It would be a table similar to it is now but will have all of the information that's in the forms view (key, name, type, scheme, in, description, etc). This will also support types other than apiKey such as oauth2, http, and openIdConnect.

**Comment by john-doe-2016** [comment]
Hi @lottamus ,

I think it would be great: like you said, it would cover other types of security than those based on header.

Regards

**Comment by chris-miaskowski** [comment]
Hey @lottamus, hi @ssspear is that going out in 1.9.0? I didn't a PR to platform-internal. If yes, can you please link that to a relevant PR? I don't recall that feature and would like to double check it got to the on-prem.

**Comment by chris-miaskowski** [comment]
Actually, no need to follow up - all good in 1.9.0.
