### ISSUE TITLE
Docs not in alphabetic order

### ISSUE THREAD

**Issue by mrum-cuscal** [stoplightio/studio#266]
**Describe the bug**
Once an API is published the output is viewed on the Docs tab.  The list of Model objects is not alphabetic but appears random

**To Reproduce**

1. Create a few model objects
2. Publish docs
3. View docs and see the model objects are not sorted alphabetically

**Expected behavior**
Model objects should be sorted alphabetically

**Screenshots**

**Environment (remove any that are not applicable):**

![Capture](https://user-images.githubusercontent.com/55524081/70201783-be4edb80-176b-11ea-8d72-43960280467a.PNG)

**Additional Context**

1. We just need to sort the tag contents by the name property here: https://github.com/stoplightio/elements/blob/c9028d42e97a5b7943800d6b268746e32f4046c2/src/hooks/useComputeToc.tsx#L166

For example:
```ts
for (const tagChild of sortyBy(tags[tag], 'name')) {
```

2. We should add a test that specifically for alphabetically sorting tagged models

**Comment by StoplightDeb** [comment]
@ssspear - is this for release 1.7.0?

**Comment by StoplightDeb** [comment]
@lottamus - I'm not sure that the changes made it to staging, I am seeing this now (API created, with a bunch of single models for it.  but it's also showing the endpoints?)![Screen Shot 2019-12-16 at 4.41.25 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/6c3c09e2-f922-418d-b50b-0a748bb7ccfb)

**Comment by chris-miaskowski** [comment]
Verified on staging just now, looks good. Moving to approved and will close once tests added to testrails

**Comment by StoplightDeb** [comment]
@chris-miaskowski , @ssspear - I discovered accidentally that mixing upper and lower cases for the first letter of model names will prevent alphabetization.

Before, a mix of upper and lower case:
![Screen Shot 2019-12-17 at 5.07.29 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/c37d783b-405e-49e9-b6ae-f60ebe0f6b0b)

After changing so that all are upper-case:
![Screen Shot 2019-12-17 at 5.09.11 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/98641eb9-4f00-4f6b-ac39-040db2137fd6)

After changing so that all are lower-case:
![Screen Shot 2019-12-17 at 5.10.28 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/33621093-c8f7-4fad-98cc-d5aa7c33e7bf)

As far as I can tell, it is alphabetizing the uppercase ones first, then the lower case ones.  Added a lowercase model that should have been at the top of the list:
![Screen Shot 2019-12-17 at 5.13.48 PM.png](https://images.zenhubusercontent.com/5d3efbd1bd5b410bba3cd46d/77436582-c5af-41fc-afd3-7bdea37b5a92)

Can we fix on this ticket before closing? cc @lottamus

**Comment by chris-miaskowski** [comment]
Yup, standard sorting algorithm will sort upper case first IIRC. I'd hesitate to say it's incorrect. It makes sense to some degree. @lottamus and @ssspear your call!

**Comment by ssspear** [comment]
@lottamus Do you have an opinion? I am ok with it

**Comment by mmiask** [comment]
Added 2 tests in TR for this:
https://stoplight.testrail.io/index.php?/cases/view/6097
https://stoplight.testrail.io/index.php?/cases/view/6098

**Comment by lottamus** [comment]
Ah good catch, we should probably sort on the lowercased value

@ssspear let's re-open this one and add a test for that in @stoplight/elements?

**Comment by chris-miaskowski** [comment]
@lottamus since we've already passed QA and release let's close this one. I've created a separate issue for this - splitting up will help us with keeping the records clean :) 

Here is the new issue: https://github.com/stoplightio/studio/issues/279
