### ISSUE TITLE
stoplight stopped commiting and cloning.

### ISSUE THREAD

**Issue by nunom-santos** [stoplightio/studio#389]
Stoplight desktop stopped being able to commit or clone repositories from github as of today,10/04/2020, at around 15h00 GMT
This does not happen in the web version, only on the desktop version.

To reproduce is enough to install stoplight (or use a installed instance) and try to clone a repository or make a commit into an opened one. 

I tried in different computers with different connections to the internet.

It should not happen and should work just as a few moments before.

![image](https://user-images.githubusercontent.com/61286709/79000551-c1583f00-7b44-11ea-9171-cce59521520b.png)
![image](https://user-images.githubusercontent.com/61286709/79000597-d59c3c00-7b44-11ea-824c-2f0f317df27c.png)

**Comment by philsturgeon** [comment]
Hey @nunom-santos. Do you have any more information we can possibly use, because "cloning a repo" is one of the hundreds of automated tests we have on our E2E testing which we make sure works just fine on release. 

Most likely something else is going on here, could you maybe open upthe developer console and see if there's more information hiding in there? 

<img width="399" alt="Screen Shot 2020-05-05 at 22 50 01" src="https://user-images.githubusercontent.com/67381/81119509-d09f9200-8f22-11ea-949b-256056c0ef83.png">

<img width="667" alt="Screen Shot 2020-05-05 at 22 49 57" src="https://user-images.githubusercontent.com/67381/81119513-d2695580-8f22-11ea-9cbf-511152d2ecc4.png">

@lottamus could we look into add "more information" for any errors? It's a little hard to get insight into what's happening here.

**Comment by nunom-santos** [comment]
Hello @philsturgeon,

I've been using the web version since the desktop version had the error, even after reinstalling.
Upon your message, I downloaded and installed once again. 
Well, it worked successfully, this time, without the error reported.

However, following your sugestion, on the developer console appeared an error that also appears on the web version.

![image](https://user-images.githubusercontent.com/61286709/81163041-09bd1e00-8f86-11ea-8010-af036009bcfb.png)

Nonetheless, I'm now able to clone and commit. Something changed.
Thank you for your feedback.

**Comment by philsturgeon** [comment]
I’m glad it’s working! If anything like the error you we’re having before happens again, check the console log and send things along so we can try and figure it out. Intermittent issues are the hardest to fix.

**Comment by nunom-santos** [comment]
Certainly. I'll do that.
Indeed they are the hardest to fix. I understand that.
Thank you once again.
