### ISSUE TITLE
Navigating to git project after reload takes time

### ISSUE THREAD

**Issue by chris-miaskowski** [stoplightio/studio#41]
**Where**

- Studio Web
- https://stoplight.io/p/studio/gh/stoplightio/prism

Not sure whether that's a bug or "a feature".

**What**

1. open git project (e.g. prism)
2. go to projects overview page
3. navigate back to project (prism)
4. see that it loads fast

![fast-load.gif](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/8bee3623-e70d-4463-b64a-8fb2440e41a3)

1. now go to projects overview
2. refresh the page
3. navigate to project (prism)
4. **see it's taking a lot of time to load** (processing something)

![processing-repo.gif](https://images.zenhubusercontent.com/5948db0651aa2c3057822fd0/c9d2fa8e-6171-4224-a5c7-97873424bc5b)

**Comment by marbemac** [comment]
Not fixable without significant investment - the processing stuff is basically graphite initializing. In the first (fast) case it's fast because it's already been initialized and is in memory. In order to fix the second case we'd need to re-architect graphite and studio a bit. Unless you have immediate ideas, in the interest of not accumulating issues that stick around forever, I suggest we close this for now. Giving graphite some more love later this fall is definitely on my mind though! We can revisit then?
