### ISSUE TITLE
Visualize schema relationships

### ISSUE THREAD

**Issue by nasht00** [stoplightio/studio#454]
When working with a complex schema, using multiple json schemas, with relationships, `$ref` all over the place ...

It'd be nice if I could visualize it, like a UML diagram or something similar.

**Comment by philsturgeon** [comment]
We built this already! :D 

The Enterprise on premise users have been enjoying it for a little while, and we're bringing it to everyone else in v2.0 which will be out any day now. 

<img width="921" alt="image" src="https://user-images.githubusercontent.com/67381/85554659-6acbae80-b625-11ea-986c-1bc1ee9833f9.png">

Enjoy!

**Comment by nasht00** [comment]
Hi,
Any news on Studio 2.0?

By the way, I see that Studio no longer appears on your homepage and is buried deeper in the site. Should I worry about long-term commitment?

**Comment by philsturgeon** [comment]
@nasht00 sorry for any confusion here, we've redesigned the website to coincide with out Stoplight Platform launch, and it certainly wasn't intentional to make anything feel hidden or deprioritized.

**Blog post:** https://stoplight.io/blog/stoplight-platform/
**Stoplight Platform:** https://stoplight.io/blog/stoplight-platform/

Stoplight Platform is deployed as SaaS 👆 which is now freely available, and includes the visual dependencies I was talking about. They're generally available for you to use right now. 👍 Stoplight Platform is technically "v2" for our on-premise users who download the software, for our SaaS customers they just know it as Stoplight Platform (because they aren't downloading anything!) 

Studio is one product we manage, it's the editor, which exists on the web as a module for Stoplight Platform, or downloadable as Studio Desktop. Studio Desktop v2.0 is not ready yet, because we've been focusing on getting Stoplight Platform out the door. It was a rather huge deal and we hope you enjoy it!

Of course Studio Desktop users have not been forgotten, we [released v1.12.0 in May and v1.13.0 in June](https://github.com/stoplightio/studio/releases), both of which fixed several of bugs that users had asked us to solve. 

Larger than that, the changes to Stoplight Platform benefit everyone, including Studio Desktop users. You don't need to bother with publishing anymore and can just use the webhooks that Platform gives you, you get new and improved documentation, etc. Studio Desktop v2.x will then let us make awesome integrations for those using Platform like sharing style guides across all APIs, etc., so any unimpressiveness in the v1.x changelog recently will be outshone by powerful new functionality now that our team have this successfully launched new framework to leverage.
