### ISSUE TITLE
JSON examples should be validated against the schema

### ISSUE THREAD

**Issue by bmogensen** [stoplightio/studio#459]
**User story.**
As a JSON schema designer I can write a JSON example for the schema which is then validated against the schema and the tool will clearly show if the example does not validate.

**Is your feature request related to a problem?**
This is a new feature

**Describe the solution you'd like**
When the user inputs a JSON example, currently he/she can enter whatever JSON formatted data is syntactically correct. However the JSON is not validated against the schema for which it is an example. The tool should validate the JSON data against the schema and show the validation errors to the user so that the example correctly reflects what the schema defines.

**Comment by philsturgeon** [comment]
We have the logic for this already in Spectral, but they've been turned off for a while due to the complexity and performance costs involved with doing this inside Studio.

If you'd like to enable Spectral in [a git commit hook, Continuous Integration or GitHub Action](https://meta.stoplight.io/docs/spectral/docs/guides/1-workflows.md), you'll get that feedback.

As for getting this reenabled in Studio: @P0lip do you think v2.0 will see the comeback as we've done so much to improve performance in that branch?

**Comment by P0lip** [comment]
> As for getting this reenabled in Studio: @P0lip do you think v2.0 will see the comeback as we've done so much to improve performance in that branch?


Yeah, v2 uses the same defaults as CLI does, so these rules are enabled :tada:

**Comment by philsturgeon** [comment]
Awesome! 

@bmogensen Studio Desktop v2.0 will be out real soon, and Studio Web already has most of this newness, so I'll close this one to avoid distracting the dev team.

**Comment by bmogensen** [comment]
Sounds good - any chance I can get an early bird on that one ? :D

**Comment by philsturgeon** [comment]
Sorry mate, we've not quite got it ready for beta tests yet but I do hope to set up a proper "Enable beta builds in auto-update" option in the medium term.
