### ISSUE TITLE
docs not found

### ISSUE THREAD

**Issue by atechgustavo** [stoplightio/studio#477]
**Describe the bug**
My project "AtechExecAuto" cloned from GitHub, after published, generates "Docs Not Found".

**To Reproduce**

1. Go to https://stoplight.io/p/docs/gh/atechgustavo/atechexecauto

**Expected behavior**
Docs working, like any of my other projects.

**Screenshots**

![image](https://user-images.githubusercontent.com/42281262/87350999-14b89f80-c52f-11ea-8a49-c792aa0aa606.png)

I cloned that repository on GitHub and then cloned that into Stoplight.
That duplicate (AtechExecAuto2) works like a charm.

![image](https://user-images.githubusercontent.com/42281262/87351057-32860480-c52f-11ea-9291-42db430e35ff.png)

**Environment (remove any that are not applicable):**
 - Studio online free

**Additional context**
It is interesting to notice that in the projects list, AtechExecAuto doesn't show the "atechgustavo/" prefix:

![image](https://user-images.githubusercontent.com/42281262/87351137-5e08ef00-c52f-11ea-9c1a-90f8c5783f59.png)

**Comment by philsturgeon** [comment]
Hello @atechgustavo. It seems like this one is private and your others are public, maybe you could click on the cog in top right once you've signed in, so that you can then change visibility from private to public.

As a heads up, this is an older version of Studio Web, and the documentation URLs have improved too. They're now shorter, and customizable.

Check out the blog post from Marc the CEO over here: https://stoplight.io/blog/stoplight-platform/

If you head over to [Stoplight Platform](https://stoplight.io/welcome/create) you can make a workspace, and set up auto publishing so you never need to worry about clicking publish again. 🥳 

Let me know if you have any trouble.

**Comment by atechgustavo** [comment]
Hey Phil,
Thank you very much for your reply.

Unfortunately, there is no cog in the top right corner:

[image: image.png]

Neither at Studio home or inside the project:

[image: image.png]

There is a cog at the lower left, but it gives no option to change the
project visibility:

[image: image.png]

What really happened here was: this repository at GitHub was private at
first when it was cloned to Stoplight.
Then, I changed that repos visibility in GitHub to public, but that didn't
seem to fix the problem in Stoplight.
So I deleted the project in Stoplight and ran a new clone. To no avail. It
seems like something kept on register inside Stoplight's database.

Well, I'll give a try on the new Studio, as you mentioned.
BR



*Gustavo Regal*
+55 51 995-965-533
linkedin.com/in/gustavoregal <https://www.linkedin.com/in/gustavoregal>
www.automatech.com.br


Em ter., 14 de jul. de 2020 às 14:45, Phil Sturgeon <
notifications@github.com> escreveu:
