### ISSUE TITLE
Do not remove YAML block opening syntax

### ISSUE THREAD

**Issue by igregson** [stoplightio/studio#484]
**Describe the bug**

One of the reasons my company is evaluating Stoplight is due to it allowing us to keep our existing review process with PRs. This means that any non-explicit changes that Stoplight makes are undesired (as they make for _really_ noisy diffs). For example: I make a small change (such as fixing a typo in a description field) and Stoplight reformats our entire spec file. After a good amount of trial and error, I attempted to get our YAML spec file in sync with any changes Stoplight would otherwise make. For all of our description properties, I opened them with the block opening syntax that Stoplight uses (`|-`). This is so that developers who do not use the studio (and just use their text editor) will not use a different block opening syntax that Stoplight would then overwrite. Learning that Stoplight removes most of these, however, breaks this approach.

**Expected behavior**

Stoplight should not remove block opening syntax (`|-`). It should also not replace single-quotes-as-apostrophes with double single quotes.

**Screenshots**

![image](https://user-images.githubusercontent.com/2054975/89357451-5e4f6280-d675-11ea-85bb-07d444490b6f.png)

**Comment by philsturgeon** [comment]
@igregson hey there! I hear you, I reported this bug back in #299 and we marked it as closed due to having a workaround, with a longer term plan to try and figure out how to avoid it happening at all. 

The workaround is setting a longer [lineWidth in project config](https://meta.stoplight.io/docs/platform/2.-workspaces/c.config.md#editor), which is not ideal, but will avoid triggering this rewrite, which should avoid changing the multi-line thing (because once the YAML is converted into an AST and back again we've got no way of knowing which exact multi-line operator was used anyway).

There is also https://github.com/stoplightio/studio/issues/447 which will allow folks to pick the multiline they prefer, and another plan which doesn't have a public ticket to rejiggle how we handle diffing. So you know, this will not happen in JSON, but our internal logic converts everything to JSON and back to YAML again, which sounds daft but there's a lot of good reasons why things were built this way. If we can find a way to handle both JSON And YAML natively, this issue, and other "YAML rewrites" will magically go away in the near to mid future, but hopefully the workaround helps enough for now.
