### ISSUE TITLE
Non JSON request bodies are not supported

### ISSUE THREAD

**Issue by captn3m0** [stoplightio/studio#493]
**Describe the bug**

Attempting to create a non-JSON request body as a sample results in a JSON validation error

**To Reproduce**

1. Create a sample body
2. Set the request body type to application/x-www-form-urlencoded
3. Set the sample body to `A=B`
4. Click outside the sample body box

I get a `Invalid JSON: Unexpected token A in JSON at position 0` error

**Expected behavior**
The sample body is accepted as a valid value.

**Screenshots**
![image](https://user-images.githubusercontent.com/584253/91228506-fb1d9100-e745-11ea-8e10-3598a9f50f18.png)

**Environment (remove any that are not applicable):**
 - Studio version: 1.13.1
 - OS: Arch Linux

**Comment by rossmcdonald** [comment]
Thanks @captn3m0! This issue has already been fixed in an upcoming v2 release. If you'd like to take a peek, you can use the web version of Studio [here](https://stoplight.io/welcome) which is already using v2. Otherwise you'll need to wait for the v2 desktop release, which should be available in the next month or two.
