### ISSUE TITLE
Multiple heades with same key

### ISSUE THREAD

**Issue by checkin247** [stoplightio/studio#505]
**Describe the bug**
Server may return multiple HEADERS with the same key.
Trying to add a second key with the same name in the response, will overwrite the first one

**To Reproduce**
1. Add a new path, response may be 204
2. Add first header to that response, for instance `Set-Cookie`
3. Try to add a second header with the same key as in step 2

**Expected behavior**
Allow adding multiple header s with the same key

**Screenshots**
adding first header:
![image](https://user-images.githubusercontent.com/12472764/95671267-19740a80-0b95-11eb-9597-0d5c80a05f15.png)

adding second header just before clicking outside the field
![image](https://user-images.githubusercontent.com/12472764/95671275-38729c80-0b95-11eb-8fca-d663f08fedc8.png)

second header did overwrite the first one
![image](https://user-images.githubusercontent.com/12472764/95671276-40324100-0b95-11eb-8aef-bf84f72ef00e.png)

**Environment (remove any that are not applicable):**
 - Studio version: [1.3  , 2.0.0.58956]
 - OS: [e.g. Windows 10]
 - Browser: [Studio / Electron]

**Additional context**
Typical header would look like this:
![image](https://user-images.githubusercontent.com/12472764/95671317-c8184b00-0b95-11eb-8dc1-c6923786677e.png)

**Comment by philsturgeon** [comment]
Hey @checkin247, this is a known case for OpenAPI, they do not allow multiple headers with the same name.

- https://github.com/OAI/OpenAPI-Specification/issues/1572
- https://github.com/OAI/OpenAPI-Specification/issues/1237

We are somewhat restrained by what OpenAPI allows, because every time we create a workaround or convention that is not in the spec, there's a chance for confusion with other tooling. Perhaps you could make a case on one of these two issues?

**Comment by checkin247** [comment]
@philsturgeon 
Understand, thank you.
I will check the issues you mentioned.
