### ISSUE TITLE
No straightforward way to create param in cookie

### ISSUE THREAD

**Issue by jfayot** [stoplightio/studio#512]
**User story.**
As an API designer, I'd like to be able to create a cookie type parameter directly from the form view, so that I don't have to move back and forth between form view and code view.

**Is your feature request related to a problem?**
Currently, when I need to create a parameter in cookie, I first create a query parameter, then I switch to the code view, change "in: query" into "in: cookie", and go back to form view to continue my design. Moreover, the modified parameter appears correctly in the preview, but disappears from the form view, which requires me to switch back and forth between form and code views every time I need to update this parameter.

**Describe the solution you'd like**
Not sure, but parameters could be first created agnostically, then updated in the "other properties" view with an additional "in" field.

**Additional context**
Not sure again, as I am an OpenAPI beginner, but is this way of designing related to OpenAPI v3 vs v2 compatibility ?

**Comment by philsturgeon** [comment]
Thanks @jfayot! Generally we're trying to switch to roadmap.stoplight.io for feature requests. I've submitted this feedback over there, but if you have any more please create it with an email address so you can get updates when we work on it!

We chose to skip cookies and focus on other important things for APIs design at first, because cookies for APIs are not all that popular. Our work is prioritized by user requests so the more things are requested the more likely we are to do it, so thanks for voting for this feature!

**Comment by philsturgeon** [comment]
This has been done @jfayot! It's in Studio Web right now for OpenAPI v3.0, and it'll be in the new Studio Desktop release. Enjoy!
