### ISSUE TITLE
Operating on gitlab causes Clone failed with: Expected "# service=git-upload-pack\n" but received "". error

### ISSUE THREAD

**Issue by stevevg** [stoplightio/studio#514]
**Describe the bug**
When trying to clone an existing project from a private gitlab repository, it fails with the message 
`Clone failed with: Expected "# service=git-upload-pack\n" but received "".`

**To Reproduce**

1. From the main page, clone a repository hosted on a private gitlab instance
2. Click Clone
3. See error

**Expected behavior**
I'd expect the repo to be cloned locally

**Screenshots**
![image](https://user-images.githubusercontent.com/2536019/99104252-11b6e400-25e1-11eb-9923-3b89be7713b7.png)

**Environment (remove any that are not applicable):**
 - Studio version: 2.1.0.66630
 - OS: Windows 10

**Additional context**
Tried to login with both password and token. Same error occurs also when trying to pull from an already cloned local API folder or switching branches.

**Comment by petrosp** [comment]
I receive the same error message when I use the Desktop application _only_ ; it appears that the web application does not suffer from this. 

I can also confirm that this happens when operating on a Gitlab repo _only_, not matter if the repo is local or remote, no matter if I first create it locally or directly clone it: I have tried a private Gitlab instance and gitlab.com; also using a public or a private repo. It makes no difference, the error still persists.

To be clear, `Github.com` works as expected.

**Comment by mdmm13** [comment]
Same problem here on Windows 10. This can be resolved by manually downgrading to 2.0.0.58956 and suppressing the auto-update to 2.1.x. Start Studio via the 2.0.0.x install file, local data remains unchanged even if edited via 2.1.x.

**Comment by stevevg** [comment]
Thanks @mdmm13 for the workaround.
By the way, I don't know how to suppress the auto-update feature. Could you please provide more info about this?

**Comment by mdmm13** [comment]
You can only suppress it while it's running (the popup), but it will update on closing, so I'm afraid the only workaround I know so far is to start it via the 2.0.0.x install file every time until the bug is fixed. You could probably try to block the auto-update network requests, but IMO not worth the effort. 

Haven't gotten around to looking for the breaking change in 2.1 vs 2.0.

**Comment by wmhilton** [comment]
@stevevg Thank you for reporting this and for your patience! This issue with cloning from GitLab should be fixed in the latest release, Studio Desktop [version 2.2.0-stable.5282.b08742e](https://github.com/stoplightio/studio/releases/tag/v2.2.0-stable.5282.b08742e). We’ll close this issue as done, but feel free to create a new issue if you find another bug!
