### ISSUE TITLE
Stoplight Studio will not stop asking for git credentials and there is no way to disable the git integration

### ISSUE THREAD

**Issue by brlutz** [stoplightio/studio#526]
**Describe the bug**
If you open a folder with a git repository, stoplight continues to prompt you for git credentials, even if you can't grant the application access, and dismiss the prompt. There is no way to turn the git integration off.

**To Reproduce**

1. Open stoplight studio
2. Open a folder with a .git folder
3. Close the window for the git credentials
4. Use the application as intended
5. See the request for git credentials pop up again

**Expected behavior**
You should be able to disable the prompts for git integration

**Environment (remove any that are not applicable):**
 - Studio version: 2.2.0.75128
 - OS: Windows 10, MacOS

**Comment by philsturgeon** [comment]
Thank you, there are some known troubles with this git integration prompt and we're looking for ways to resolve it. Soon there will be a new "Web Projects" feature where you just use Stoplight Studio Web like a regular git-less SaaS, which might be more up your alley. Otherwise yeah, there will hopefully soon be a way to make that git prompt go away. I've filed this in our internal feedback tool so it'll help prioritise the work.
