### ISSUE TITLE
Setting to disable git integration

### ISSUE THREAD

**Issue by apahne** [stoplightio/studio#547]
**User story.**
As a user, I can disable constant querying for git credentials, so that I can work on APIs without interuption.

**Is your feature request related to a problem?**
I am constantly interupted with a modal window asking for git credentials. I don't want to share them as I exclusively use git on the command line. I would like to be able to stop this interruptions somehow.

**Describe the solution you'd like**
Configuration setting to disable git integration.

**Comment by lottamus** [comment]
Hey @apahne,

I believe this is happening because the Git auto-pull feature is enabled, which requires Git credentials. Let me check with the team to see if we could have that setting turned off by default if there are no credentials set.

For now if you disable it in your project settings, it should stop asking you for credentials.

![image](https://user-images.githubusercontent.com/7423098/109817217-47ff8a00-7bf7-11eb-85cb-d2f7e78c6a35.png)

**Comment by apahne** [comment]
That is already a good workaround, thank you. I wasn't aware of that option.

**Comment by philsturgeon** [comment]
That workaround should tide you over, and this roadmap card will be the solution I think you want. Please subscribe to get updates when it's out! https://roadmap.stoplight.io/c/119-option-for-collaborative-stoplight-projects-without-git
