### ISSUE TITLE
Adding example to endpoint is flagged as an error: should have required property '$ref'

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/studio#95]
**Describe the bug**
When adding an example to an operation response, an error is displayed in the diagnostics panel:

> /paths//mypath/get/responses/200 should have required property '$ref'

**To Reproduce**

1. Create an example for an HTTP response

**Screenshots**
![Screen Shot 2019-09-09 at 4 02 13 PM](https://user-images.githubusercontent.com/4060903/64568295-0488d000-d320-11e9-98a7-572565331b16.png)

**Comment by P0lip** [comment]
Most likely related to https://github.com/stoplightio/spectral/issues/403 as well as https://github.com/stoplightio/studio-internal/pull/670#issuecomment-527632302
There is not much we can do about it at the moment.
oas2-schema and oas3-schema rules are known to produce weird output.
The top priority is to have more granular checks in place, so that the schema validation does not have to be performed on the entire document.



cc @marbemac

**Comment by P0lip** [comment]
Anyhoo, in order to get the error disappear, you can fix the example.
This is how the example should look like:
```
"description": "",
"value": {
   // actual example
}
```

**Comment by marbemac** [comment]
@rossmcdonald this one snuck by the release notes (merged 22 days ago). Could you confirm fixed when you have a moment? If fixed, feel free to close etc.

**Comment by rossmcdonald** [comment]
Yep, fixed.
